apiVersion: v1
kind: Template
labels:
  application: mlflow-job

metadata:
  name: mlflow-job
  annotations:
    description: "Data Hub - MLFlow Job "
    iconClass: "icon-redis"
    tags: "mlflow,aicoe,datahub,mljob"

objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      app: ${APPLICATION_NAME}
  spec:
    parallelism: 1
    completions: 1
    template:
      metadata:
        name: ${APPLICATION_NAME}
      spec:
        containers:
        - envFrom:
          - secretRef:
              name: ${SECRET_KEY}
          image: ${IMAGE_URI}:latest
          name: ${APPLICATION_NAME}
          imagePullPolicy: Always
          resources:
            requests:
              memory: "${JOB_MEMORY_REQUEST}"
            limits:
              memory: "${JOB_MEMORY_LIMIT}"
          env:
            - name:  MLFLOW_EXPERIMENT_ID
              value: "${MLFLOW_EXPERIMENT_ID}"
            - name:  MLFLOW_TRACKING_URI
              value: "${MLFLOW_TRACKING_URI}"
            - name:  K_CLUSTERS
              value: "${INSIGHTS_K_CLUSTERS}"
            - name:  PCA_DIMENSIONS
              value: "${INSIGHTS_PCA_DIMENSIONS}"
            - name:  DAY_1
              value: "${INSIGHTS_DAY_1}"
            - name:  DAY_2
              value: "${INSIGHTS_DAY_2}"
        restartPolicy: Never

parameters:
- name: APPLICATION_NAME
  from: 'mlflow-job-[a-z0-9]{4}'
  generate: expression
- name: IMAGE_URI
  required: true
- name: MLFLOW_TRACKING_URI
  required: true
- name: MLFLOW_EXPERIMENT_ID
  required: true
- name: SECRET_KEY
  required: true
- name: JOB_CPU_REQUEST
  value: "1000m"
  required: true
- name: JOB_MEMORY_REQUEST
  value: "4Gi"
  required: true
- name: JOB_CPU_LIMIT
  value: "4000m"
  required: true
- name: JOB_MEMORY_LIMIT
  value: "16Gi"
  required: true
- name: INSIGHTS_K_CLUSTERS
  value: "4"
- name: INSIGHTS_PCA_DIMENSIONS
  value: "3"
- name: INSIGHTS_DAY_1
  value: "2018-08-20"
- name: INSIGHTS_DAY_2
  value: "2018-08-21"
- name: SECRET_KEY
  required: true
