apiVersion: v1
kind: Template
labels:
  application: mlflow-job

metadata:
  name: mlflow-job
  annotations:
    description: "Data Hub - MLFlow Job "
    tags: "mlflow,aicoe,datahub,mljob"

objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      app: ${APPLICATION_NAME}
  spec:
    parallelism: 1
    completions: 1
    template:
      metadata:
        name: ${APPLICATION_NAME}
      spec:
        containers:
        - image: ${IMAGE_URI}:latest
          name: ${APPLICATION_NAME}
          imagePullPolicy: Always
          resources:
            requests:
              memory: "${JOB_MEMORY_REQUEST}"
            limits:
              memory: "${JOB_MEMORY_LIMIT}"
          envFrom:
          - secretRef:
              name: ${SECRET_KEY}
          env:
            - name:  MLFLOW_EXPERIMENT_ID
              value: "${MLFLOW_EXPERIMENT_ID}"
            - name:  MLFLOW_TRACKING_URI
              value: "${MLFLOW_TRACKING_URI}"
        restartPolicy: Never

parameters:
- name: APPLICATION_NAME
  from: 'mlflow-job-[a-z0-9]{4}'
  generate: expression
- name: IMAGE_URI
  required: true
- name: MLFLOW_TRACKING_URI
  required: true
  value: http://mlflow-server-svc:5000/
- name: MLFLOW_EXPERIMENT_ID
  required: true
