apiVersion: v1
kind: Template
metadata:
  name: mlflow-tracking-server
  annotations:
    description: "Data Hub - MLFlow Tracking Server "
    tags: "mlflow,aicoe,datahub"
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: mlflow-server-svc
    labels:
      app: mlflow-server
  spec:
    ports:
    - port: 5000
      name: http
    selector:
      app: mlflow-server
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: mlflow-server
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: mlflow-server
          version: v${MLFLOW_VERSION}
      spec:
        containers:
        - name: "mlflow-server"
          image: "quay.io/zmhassan/mlflow:${MLFLOW_VERSION}"
          ports:
          - containerPort: 5000
parameters:
- name: MLFLOW_VERSION
  description: "MLFlow tracking server version"
  value: "0.5.0-rc13"
